import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

/**
 * Dates are formatted through src/lib/utils/time.ts, which pins Asia/Manila.
 *
 * Server Components and server actions run on Vercel in UTC, and client
 * components are prerendered there too. Formatting without a timeZone prints
 * the server's zone: anything before 8 AM in Manila lands on the previous
 * day, and every time reads eight hours early. A summons emailed with the
 * wrong hour is the failure this exists to prevent.
 *
 * A call that passes its own timeZone is allowed; the zone was chosen, not
 * inherited.
 */
const HAS_NO_TIME_ZONE = ":not(:has(Property[key.name='timeZone']))";
const USE_TIME_HELPERS =
  "without a timeZone this prints the server's zone, which is UTC on Vercel. Use the Manila helpers in @/lib/utils/time (formatManilaDate, formatManilaTime, ... or formatManila(value, options) for a one-off shape).";

const manilaDates = {
  files: ["src/**/*.{ts,tsx}"],
  ignores: [
    "src/lib/utils/time.ts",
    // shadcn primitive, regenerated by the CLI. It labels calendar-grid
    // dates that react-day-picker builds in the browser's own zone.
    "src/components/ui/calendar.tsx",
  ],
  rules: {
    "no-restricted-syntax": [
      "error",
      {
        selector: `CallExpression[callee.property.name=/^toLocale(Date|Time)String$/]${HAS_NO_TIME_ZONE}`,
        message: `Dates: ${USE_TIME_HELPERS}`,
      },
      {
        selector: `CallExpression[callee.property.name='toLocaleString']${HAS_NO_TIME_ZONE}`,
        message: `Dates: ${USE_TIME_HELPERS} Numbers: use Intl.NumberFormat.`,
      },
      {
        selector: `:matches(NewExpression, CallExpression)[callee.object.name='Intl'][callee.property.name='DateTimeFormat']${HAS_NO_TIME_ZONE}`,
        message: `Intl.DateTimeFormat: ${USE_TIME_HELPERS}`,
      },
    ],
  },
};

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  manilaDates,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
  ]),
]);

export default eslintConfig;
