-- ============================================================
-- Migration 00007: OSA Discipline & Case Management
-- ============================================================
-- Digitizes the disciplinary flow documented in the OSA process guide
-- (§2.1 and flowchart §3.1). Replaces the physical logbooks that OSA
-- currently maintains for offense tracking.
--
-- THREE RESOLUTION PATHS, mirroring the official flowchart:
--
--   MINOR   → administrative counselling → written apology letter → closed
--   MAJOR   → faculty complaint → webmail summons → in-person conference
--             → mediation → [settled] OR [escalate to PIC → SDB → sanction]
--   CONFID. → referred directly to CODI, bypassing general OSA flow
--
-- DESIGN NOTE: every state change writes to case_timeline. That table is
-- append-only and is the evidentiary record replacing the logbook. It is
-- deliberately separate from audit_logs: audit_logs tracks *who touched
-- what data*, case_timeline tracks *what happened in the case*.
-- ============================================================

-- ============================================================
-- 1. VIOLATION TYPES — catalog keyed to the TUP Student Manual
-- ============================================================
CREATE TABLE IF NOT EXISTS public.violation_types (
  id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  code                TEXT NOT NULL UNIQUE,
  name                TEXT NOT NULL,
  description         TEXT,
  -- Default classification. A case may be reclassified by OSA after review
  -- (the flowchart's "Determine Offense Classification" decision point).
  default_classification TEXT NOT NULL
    CHECK (default_classification IN ('minor', 'major', 'confidential')),
  -- Citation into the TUP Student Manual, so sanctions are traceable to policy
  handbook_reference  TEXT,
  typical_sanction    TEXT,
  -- Confidential types (harassment, etc.) auto-route to CODI and never
  -- appear in the general OSA queue.
  auto_route_codi     BOOLEAN NOT NULL DEFAULT FALSE,
  is_active           BOOLEAN NOT NULL DEFAULT TRUE,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_violation_types_classification
  ON public.violation_types(default_classification) WHERE is_active;

-- ============================================================
-- 2. VIOLATION CASES — the central record
-- ============================================================
CREATE TABLE IF NOT EXISTS public.violation_cases (
  id                UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Human-readable case number (OSA-2026-0001). Generated by trigger below
  -- so staff can reference cases verbally and on paper.
  case_number       TEXT UNIQUE,

  -- The complainee
  student_id        UUID NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,

  -- The complainant. NULL when OSA initiates on its own observation.
  complainant_staff_id UUID REFERENCES public.staff(id) ON DELETE SET NULL,
  complainant_type  TEXT NOT NULL DEFAULT 'faculty'
    CHECK (complainant_type IN ('faculty', 'staff', 'student', 'osa_initiated', 'external')),
  -- Free-text fallback when the complainant is not a system user
  complainant_name  TEXT,

  violation_type_id UUID REFERENCES public.violation_types(id) ON DELETE SET NULL,

  -- Effective classification for THIS case (may differ from the type default
  -- after OSA review — the flowchart explicitly allows reclassification).
  classification    TEXT NOT NULL
    CHECK (classification IN ('minor', 'major', 'confidential')),

  -- Incident details
  incident_date     DATE NOT NULL,
  incident_time     TIME,
  incident_location TEXT,
  description       TEXT NOT NULL CHECK (char_length(description) >= 10),

  -- Workflow state. Ordered roughly by progression, but transitions are
  -- validated in application code, not by constraint, because the OSA
  -- process legitimately allows back-transitions (reschedule, reclassify).
  status            TEXT NOT NULL DEFAULT 'filed' CHECK (status IN (
    'filed',                 -- complaint received, not yet triaged
    'under_review',          -- OSA determining classification
    'counselling_scheduled', -- MINOR path
    'awaiting_apology',      -- MINOR path: counselling done, letter pending
    'summons_sent',          -- MAJOR path: webmail dispatched
    'hearing_scheduled',     -- MAJOR path: conference booked
    'hearing_completed',
    'in_mediation',
    'settled',               -- win-win settlement reached
    'escalated_pic',         -- Preliminary Investigation Committee
    'escalated_sdb',         -- Student Disciplinary Board
    'referred_codi',         -- CONFIDENTIAL path
    'sanctioned',
    'dismissed',             -- complaint not substantiated
    'closed'
  )),

  -- Which branch of the flowchart this case ultimately took.
  -- NULL until resolution.
  resolution_path   TEXT CHECK (resolution_path IN (
    'counselling_apology', 'mediation_settlement', 'pic_sdb',
    'codi_referral', 'dismissed'
  ) OR resolution_path IS NULL),

  -- Visibility tier. 'codi' rows are invisible to general OSA staff via RLS.
  confidentiality   TEXT NOT NULL DEFAULT 'normal'
    CHECK (confidentiality IN ('normal', 'restricted', 'codi')),

  assigned_officer_id UUID REFERENCES public.staff(id) ON DELETE SET NULL,

  -- Final outcome
  sanction_applied  TEXT,
  resolution_notes  TEXT,

  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  closed_at         TIMESTAMPTZ,

  -- A case cannot be closed without a resolution path recorded.
  CONSTRAINT closed_requires_resolution CHECK (
    closed_at IS NULL OR resolution_path IS NOT NULL
  )
);

CREATE INDEX IF NOT EXISTS idx_cases_student     ON public.violation_cases(student_id);
CREATE INDEX IF NOT EXISTS idx_cases_status      ON public.violation_cases(status);
CREATE INDEX IF NOT EXISTS idx_cases_class       ON public.violation_cases(classification);
CREATE INDEX IF NOT EXISTS idx_cases_officer     ON public.violation_cases(assigned_officer_id);
CREATE INDEX IF NOT EXISTS idx_cases_complainant ON public.violation_cases(complainant_staff_id);
CREATE INDEX IF NOT EXISTS idx_cases_created     ON public.violation_cases(created_at DESC);
-- Partial index for the "open cases" queue, which is the hottest query.
CREATE INDEX IF NOT EXISTS idx_cases_open ON public.violation_cases(created_at DESC)
  WHERE status NOT IN ('closed', 'dismissed');

-- ---- Case number generation ----
-- Format: OSA-<year>-<zero-padded sequence within that year>
CREATE SEQUENCE IF NOT EXISTS public.case_number_seq;

CREATE OR REPLACE FUNCTION public.generate_case_number()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  yr TEXT := to_char(NOW(), 'YYYY');
  seq_val BIGINT;
BEGIN
  IF NEW.case_number IS NULL THEN
    -- Count existing cases this year rather than a global sequence, so the
    -- number restarts at 0001 each January (matches OSA's paper convention).
    SELECT COUNT(*) + 1 INTO seq_val
    FROM public.violation_cases
    WHERE date_part('year', created_at) = date_part('year', NOW());

    NEW.case_number := 'OSA-' || yr || '-' || lpad(seq_val::TEXT, 4, '0');
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_case_number ON public.violation_cases;
CREATE TRIGGER trg_case_number
  BEFORE INSERT ON public.violation_cases
  FOR EACH ROW EXECUTE FUNCTION public.generate_case_number();

DROP TRIGGER IF EXISTS trg_cases_updated_at ON public.violation_cases;
CREATE TRIGGER trg_cases_updated_at
  BEFORE UPDATE ON public.violation_cases
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- ============================================================
-- 3. CASE TIMELINE — append-only evidentiary log
-- ============================================================
-- This is the digital replacement for the physical logbook. No UPDATE or
-- DELETE policy is ever granted (see migration 00013), so entries cannot
-- be altered after the fact. Required for due-process defensibility if a
-- sanction is ever contested.
CREATE TABLE IF NOT EXISTS public.case_timeline (
  id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  case_id      UUID NOT NULL REFERENCES public.violation_cases(id) ON DELETE CASCADE,
  actor_id     UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  actor_label  TEXT,   -- denormalized name, preserved even if the user is deleted
  event_type   TEXT NOT NULL CHECK (event_type IN (
    'case_filed', 'classified', 'reclassified', 'assigned',
    'summons_sent', 'slots_proposed', 'schedule_approved',
    'student_notified', 'student_acknowledged',
    'hearing_held', 'hearing_rescheduled', 'no_show',
    'apology_submitted', 'apology_accepted', 'apology_rejected',
    'settlement_drafted', 'settlement_signed',
    'escalated', 'sanction_applied', 'dismissed', 'closed',
    'note_added', 'document_uploaded', 'status_changed'
  )),
  from_status  TEXT,
  to_status    TEXT,
  summary      TEXT NOT NULL,
  details      JSONB,
  occurred_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_timeline_case
  ON public.case_timeline(case_id, occurred_at);

-- ============================================================
-- 4. CASE DOCUMENTS — complaint letters and evidence
-- ============================================================
CREATE TABLE IF NOT EXISTS public.case_documents (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  case_id       UUID NOT NULL REFERENCES public.violation_cases(id) ON DELETE CASCADE,
  uploaded_by   UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  document_type TEXT NOT NULL CHECK (document_type IN (
    'complaint_letter', 'evidence', 'apology_letter',
    'settlement_agreement', 'sanction_notice', 'summons_copy', 'other'
  )),
  file_name     TEXT NOT NULL,
  file_path     TEXT NOT NULL,
  file_size     INT NOT NULL CHECK (file_size > 0 AND file_size <= 10485760),
  mime_type     TEXT NOT NULL,
  -- Whether the student may view this document. Investigation notes and
  -- some evidence stay staff-only until the hearing.
  visible_to_student BOOLEAN NOT NULL DEFAULT FALSE,
  uploaded_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_case_docs_case ON public.case_documents(case_id);

-- ============================================================
-- 5. CASE HEARINGS — the in-person conference
-- ============================================================
-- Status flow implements requirement #1 precisely:
--   AI proposes slots → complainant (professor) approves ONE
--   → student is notified → student acknowledges → hearing held
CREATE TABLE IF NOT EXISTS public.case_hearings (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  case_id         UUID NOT NULL REFERENCES public.violation_cases(id) ON DELETE CASCADE,

  hearing_type    TEXT NOT NULL DEFAULT 'conference' CHECK (hearing_type IN (
    'counselling',   -- MINOR path administrative counselling
    'conference',    -- MAJOR path in-person consultation
    'mediation',
    'pic_hearing',
    'sdb_hearing',
    'follow_up'
  )),

  scheduled_start TIMESTAMPTZ NOT NULL,
  scheduled_end   TIMESTAMPTZ NOT NULL,
  venue           TEXT NOT NULL DEFAULT 'OSA Office',

  status          TEXT NOT NULL DEFAULT 'awaiting_complainant' CHECK (status IN (
    'awaiting_complainant',  -- AI picked a slot; professor must approve
    'complainant_approved',  -- professor said yes; ready to notify student
    'student_notified',      -- summons dispatched via webmail + portal
    'student_acknowledged',  -- student confirmed receipt in the portal
    'confirmed',
    'completed',
    'rescheduled',
    'cancelled',
    'no_show_student',
    'no_show_complainant'
  )),

  -- Who/what proposed this slot. 'system' means the scheduling algorithm.
  proposed_by     TEXT NOT NULL DEFAULT 'system'
    CHECK (proposed_by IN ('system', 'staff', 'complainant')),

  -- Approval chain timestamps — each is evidence of due process
  complainant_approved_by  UUID REFERENCES public.staff(id) ON DELETE SET NULL,
  complainant_approved_at  TIMESTAMPTZ,
  student_notified_at      TIMESTAMPTZ,
  student_acknowledged_at  TIMESTAMPTZ,

  -- Notification delivery tracking (req #4: portal OR university email)
  notified_via_email   BOOLEAN NOT NULL DEFAULT FALSE,
  notified_via_portal  BOOLEAN NOT NULL DEFAULT FALSE,

  meeting_notes   TEXT,
  outcome         TEXT CHECK (outcome IN (
    'settled', 'escalated', 'apology_agreed', 'dismissed',
    'follow_up_required', 'no_resolution'
  ) OR outcome IS NULL),

  completed_at    TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CHECK (scheduled_end > scheduled_start),
  -- The student may not be notified before the complainant has approved.
  -- This enforces requirement #1's ordering at the database level.
  CONSTRAINT notify_requires_approval CHECK (
    student_notified_at IS NULL OR complainant_approved_at IS NOT NULL
  )
);

CREATE INDEX IF NOT EXISTS idx_hearings_case   ON public.case_hearings(case_id);
CREATE INDEX IF NOT EXISTS idx_hearings_start  ON public.case_hearings(scheduled_start);
CREATE INDEX IF NOT EXISTS idx_hearings_status ON public.case_hearings(status);

DROP TRIGGER IF EXISTS trg_hearings_updated_at ON public.case_hearings;
CREATE TRIGGER trg_hearings_updated_at
  BEFORE UPDATE ON public.case_hearings
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- ============================================================
-- 6. APOLOGY LETTERS — MINOR offense resolution artifact
-- ============================================================
CREATE TABLE IF NOT EXISTS public.apology_letters (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  case_id       UUID NOT NULL REFERENCES public.violation_cases(id) ON DELETE CASCADE,
  student_id    UUID NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  -- Either typed directly in the portal or uploaded as a signed scan
  letter_text   TEXT,
  file_path     TEXT,
  submitted_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  review_status TEXT NOT NULL DEFAULT 'pending'
    CHECK (review_status IN ('pending', 'accepted', 'revision_requested', 'rejected')),
  reviewed_by   UUID REFERENCES public.staff(id) ON DELETE SET NULL,
  reviewed_at   TIMESTAMPTZ,
  reviewer_notes TEXT,
  -- Must contain something
  CONSTRAINT letter_has_content CHECK (
    letter_text IS NOT NULL OR file_path IS NOT NULL
  )
);

CREATE INDEX IF NOT EXISTS idx_apology_case ON public.apology_letters(case_id);

-- ============================================================
-- 7. SETTLEMENTS — the "win-win" agreement from the flowchart
-- ============================================================
CREATE TABLE IF NOT EXISTS public.case_settlements (
  id             UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  case_id        UUID NOT NULL REFERENCES public.violation_cases(id) ON DELETE CASCADE,
  hearing_id     UUID REFERENCES public.case_hearings(id) ON DELETE SET NULL,
  terms          TEXT NOT NULL CHECK (char_length(terms) >= 10),
  -- Any commitments the student agreed to (community service, restitution…)
  student_obligations TEXT,
  compliance_deadline DATE,

  -- Tri-party signature record. All three must be present for the settlement
  -- to take effect; enforced in application code and surfaced in the UI.
  student_signed_at     TIMESTAMPTZ,
  complainant_signed_at TIMESTAMPTZ,
  osa_witnessed_by      UUID REFERENCES public.staff(id) ON DELETE SET NULL,
  osa_witnessed_at      TIMESTAMPTZ,

  is_complied    BOOLEAN,
  complied_at    TIMESTAMPTZ,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_settlements_case ON public.case_settlements(case_id);

-- ============================================================
-- 8. CASE ESCALATIONS — PIC / SDB / CODI referral chain
-- ============================================================
CREATE TABLE IF NOT EXISTS public.case_escalations (
  id             UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  case_id        UUID NOT NULL REFERENCES public.violation_cases(id) ON DELETE CASCADE,
  escalated_to   TEXT NOT NULL CHECK (escalated_to IN ('PIC', 'SDB', 'CODI')),
  escalated_by   UUID REFERENCES public.staff(id) ON DELETE SET NULL,
  reason         TEXT NOT NULL,
  escalated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Committee outcome. NULL while deliberation is ongoing.
  outcome        TEXT CHECK (outcome IN (
    'upheld', 'dismissed', 'referred_further', 'sanction_recommended', 'pending'
  ) OR outcome IS NULL),
  outcome_notes  TEXT,
  sanction_recommended TEXT,
  decided_at     TIMESTAMPTZ,

  -- Committee reference number from the physical/parallel process
  external_reference TEXT
);

CREATE INDEX IF NOT EXISTS idx_escalations_case ON public.case_escalations(case_id);
CREATE INDEX IF NOT EXISTS idx_escalations_body ON public.case_escalations(escalated_to);

-- ============================================================
-- 9. SEED: violation types from the TUP Student Manual
-- ============================================================
INSERT INTO public.violation_types
  (code, name, description, default_classification, handbook_reference, typical_sanction, auto_route_codi)
VALUES
  -- MINOR
  ('MIN-01', 'Improper Uniform / Dress Code',
   'Failure to wear the prescribed uniform or ID within campus premises.',
   'minor', 'Student Manual Art. VIII §1', 'Administrative counselling + written apology', FALSE),
  ('MIN-02', 'Tardiness / Unexcused Absence',
   'Habitual tardiness or unexcused absence from classes or required activities.',
   'minor', 'Student Manual Art. VIII §2', 'Administrative counselling + written apology', FALSE),
  ('MIN-03', 'Littering / Improper Waste Disposal',
   'Disposal of waste outside designated receptacles.',
   'minor', 'Student Manual Art. VIII §3', 'Administrative counselling + community service', FALSE),
  ('MIN-04', 'Unauthorized Use of Facilities',
   'Use of laboratories, rooms, or equipment without proper authorization.',
   'minor', 'Student Manual Art. VIII §4', 'Administrative counselling + written apology', FALSE),
  ('MIN-05', 'Disruptive Behavior in Class',
   'Conduct that disrupts the orderly conduct of classes.',
   'minor', 'Student Manual Art. VIII §5', 'Administrative counselling', FALSE),

  -- MAJOR
  ('MAJ-01', 'Academic Dishonesty',
   'Cheating, plagiarism, falsification of academic records, or contract cheating.',
   'major', 'Student Manual Art. IX §1', 'Suspension; grade of 5.0 in the subject', FALSE),
  ('MAJ-02', 'Vandalism / Destruction of Property',
   'Willful damage or defacement of university property.',
   'major', 'Student Manual Art. IX §2', 'Restitution + suspension', FALSE),
  ('MAJ-03', 'Physical Altercation',
   'Fighting or inflicting physical harm on another member of the community.',
   'major', 'Student Manual Art. IX §3', 'Suspension; possible exclusion', FALSE),
  ('MAJ-04', 'Theft',
   'Taking property belonging to another person or the university.',
   'major', 'Student Manual Art. IX §4', 'Restitution + suspension or exclusion', FALSE),
  ('MAJ-05', 'Falsification of Documents',
   'Forging signatures, tampering with official documents or receipts.',
   'major', 'Student Manual Art. IX §5', 'Suspension or exclusion', FALSE),
  ('MAJ-06', 'Substance Use on Campus',
   'Possession or use of alcohol or prohibited substances within campus.',
   'major', 'Student Manual Art. IX §6', 'Suspension + mandatory counselling', FALSE),
  ('MAJ-07', 'Bullying / Cyberbullying',
   'Repeated aggressive behavior, in person or online, against a member of the community.',
   'major', 'Student Manual Art. IX §7 / RA 10627', 'Suspension + mandatory counselling', FALSE),

  -- CONFIDENTIAL → CODI (bypasses general OSA flow per the process document)
  ('CON-01', 'Sexual Harassment',
   'Any form of sexual harassment as defined under RA 7877 and RA 11313.',
   'confidential', 'RA 7877 / RA 11313 · CODI jurisdiction',
   'Determined by the Committee on Decorum and Investigation', TRUE),
  ('CON-02', 'Gender-Based Violence',
   'Gender-based violence or discrimination under the Safe Spaces Act.',
   'confidential', 'RA 11313 · CODI jurisdiction',
   'Determined by the Committee on Decorum and Investigation', TRUE),
  ('CON-03', 'Discrimination',
   'Discrimination on the basis of protected characteristics.',
   'confidential', 'CODI jurisdiction',
   'Determined by the Committee on Decorum and Investigation', TRUE)
ON CONFLICT (code) DO NOTHING;
